name=PofoSmartCable
architectures=*
version=0.0.0-SNAPSHOT
author=Petr Kracik
maintainer=Petr Kracik <petrkr@petrkr.net>
sentence=Library for Atari portfolio SmartCable protocol
paragraph=Currently supports bit-bang protocol
category=
url=https://github.com/petrkr/PofoSmartCable
