name=PofoSmartCable
architectures=*
version=0.0.0-SNAPSHOT
author=Petr Kracik
maintainer=Petr Kracik <petrkr@petrkr.net>
sentence=Library for Atari portfolio SmartCable protocol
paragraph=ESP32 Arduino library for the Atari Portfolio Smart Cable protocol.
category=Communication
url=https://github.com/petrkr/PofoSmartCable
